services:
     mysql:
          image: mysql:8.4
          container_name: mini-chat-mysql
          environment:
               MYSQL_ROOT_PASSWORD: root
               MYSQL_DATABASE: mini_chat_auth
          ports:
               - "3306:3306"
          volumes:
               - mysql_data:/var/lib/mysql
          healthcheck:
               test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
               interval: 10s
               timeout: 5s
               retries: 10

     mongodb:
          image: mongo:7
          container_name: mini-chat-mongo
          ports:
               - "27017:27017"
          volumes:
               - mongo_data:/data/db
          healthcheck:
               test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
               interval: 10s
               timeout: 5s
               retries: 10

     redis:
          image: redis:7-alpine
          container_name: mini-chat-redis
          ports:
               - "6379:6379"
          volumes:
               - redis_data:/data
          healthcheck:
               test: ["CMD", "redis-cli", "ping"]
               interval: 10s
               timeout: 5s
               retries: 10

volumes:
     mysql_data:
     mongo_data:
     redis_data:
